// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/serialization.js/src/js.proto

package org.jetbrains.kotlin.serialization.js;

import com.google.protobuf.*;

import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectStreamException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public final class JsProtoBuf {
  private JsProtoBuf() {}
  public static void registerAllExtensions(
      ExtensionRegistryLite registry) {
  }
  public interface ContentOrBuilder
      extends MessageLiteOrBuilder {

    // repeated .org.jetbrains.kotlin.serialization.js.Content.Entry entry = 1;
    /**
     * <code>repeated .org.jetbrains.kotlin.serialization.js.Content.Entry entry = 1;</code>
     */
    List<org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content.Entry>
        getEntryList();
    /**
     * <code>repeated .org.jetbrains.kotlin.serialization.js.Content.Entry entry = 1;</code>
     */
    org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content.Entry getEntry(int index);
    /**
     * <code>repeated .org.jetbrains.kotlin.serialization.js.Content.Entry entry = 1;</code>
     */
    int getEntryCount();
  }
  /**
   * Protobuf type {@code org.jetbrains.kotlin.serialization.js.Content}
   */
  public static final class Content extends
      GeneratedMessageLite
      implements ContentOrBuilder {
    // Use Content.newBuilder() to construct.
    private Content(GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private Content(boolean noInit) {}

    private static final Content defaultInstance;
    public static Content getDefaultInstance() {
      return defaultInstance;
    }

    public Content getDefaultInstanceForType() {
      return defaultInstance;
    }

    private Content(
        CodedInputStream input,
        ExtensionRegistryLite extensionRegistry)
        throws InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                entry_ = new ArrayList<org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content.Entry>();
                mutable_bitField0_ |= 0x00000001;
              }
              entry_.add(input.readMessage(org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content.Entry.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (IOException e) {
        throw new InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          entry_ = Collections.unmodifiableList(entry_);
        }
        makeExtensionsImmutable();
      }
    }
    public static Parser<Content> PARSER =
        new AbstractParser<Content>() {
      public Content parsePartialFrom(
          CodedInputStream input,
          ExtensionRegistryLite extensionRegistry)
          throws InvalidProtocolBufferException {
        return new Content(input, extensionRegistry);
      }
    };

    @Override
    public Parser<Content> getParserForType() {
      return PARSER;
    }

    public interface EntryOrBuilder
        extends MessageLiteOrBuilder {

      // required string name = 1;
      /**
       * <code>required string name = 1;</code>
       */
      boolean hasName();
      /**
       * <code>required string name = 1;</code>
       */
      String getName();
      /**
       * <code>required string name = 1;</code>
       */
      ByteString
          getNameBytes();

      // required bytes body = 2;
      /**
       * <code>required bytes body = 2;</code>
       */
      boolean hasBody();
      /**
       * <code>required bytes body = 2;</code>
       */
      ByteString getBody();
    }
    /**
     * Protobuf type {@code org.jetbrains.kotlin.serialization.js.Content.Entry}
     */
    public static final class Entry extends
        GeneratedMessageLite
        implements EntryOrBuilder {
      // Use Entry.newBuilder() to construct.
      private Entry(GeneratedMessageLite.Builder builder) {
        super(builder);

      }
      private Entry(boolean noInit) {}

      private static final Entry defaultInstance;
      public static Entry getDefaultInstance() {
        return defaultInstance;
      }

      public Entry getDefaultInstanceForType() {
        return defaultInstance;
      }

      private Entry(
          CodedInputStream input,
          ExtensionRegistryLite extensionRegistry)
          throws InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                name_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                body_ = input.readBytes();
                break;
              }
            }
          }
        } catch (InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (IOException e) {
          throw new InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static Parser<Entry> PARSER =
          new AbstractParser<Entry>() {
        public Entry parsePartialFrom(
            CodedInputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws InvalidProtocolBufferException {
          return new Entry(input, extensionRegistry);
        }
      };

      @Override
      public Parser<Entry> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string name = 1;
      public static final int NAME_FIELD_NUMBER = 1;
      private Object name_;
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public String getName() {
        Object ref = name_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          ByteString bs =
              (ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          ByteString b =
              ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (ByteString) ref;
        }
      }

      // required bytes body = 2;
      public static final int BODY_FIELD_NUMBER = 2;
      private ByteString body_;
      /**
       * <code>required bytes body = 2;</code>
       */
      public boolean hasBody() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes body = 2;</code>
       */
      public ByteString getBody() {
        return body_;
      }

      private void initFields() {
        name_ = "";
        body_ = ByteString.EMPTY;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasBody()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(CodedOutputStream output)
                          throws IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, body_);
        }
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += CodedOutputStream
            .computeBytesSize(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += CodedOutputStream
            .computeBytesSize(2, body_);
        }
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @Override
      protected Object writeReplace()
          throws ObjectStreamException {
        return super.writeReplace();
      }

      public static org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content.Entry parseFrom(
          ByteString data)
          throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content.Entry parseFrom(
          ByteString data,
          ExtensionRegistryLite extensionRegistry)
          throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content.Entry parseFrom(byte[] data)
          throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content.Entry parseFrom(
          byte[] data,
          ExtensionRegistryLite extensionRegistry)
          throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content.Entry parseFrom(InputStream input)
          throws IOException {
        return PARSER.parseFrom(input);
      }
      public static org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content.Entry parseFrom(
          InputStream input,
          ExtensionRegistryLite extensionRegistry)
          throws IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content.Entry parseDelimitedFrom(InputStream input)
          throws IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content.Entry parseDelimitedFrom(
          InputStream input,
          ExtensionRegistryLite extensionRegistry)
          throws IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content.Entry parseFrom(
          CodedInputStream input)
          throws IOException {
        return PARSER.parseFrom(input);
      }
      public static org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content.Entry parseFrom(
          CodedInputStream input,
          ExtensionRegistryLite extensionRegistry)
          throws IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content.Entry prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      /**
       * Protobuf type {@code org.jetbrains.kotlin.serialization.js.Content.Entry}
       */
      public static final class Builder extends
          GeneratedMessageLite.Builder<
            org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content.Entry, Builder>
          implements org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content.EntryOrBuilder {
        // Construct using org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content.Entry.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          name_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          body_ = ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content.Entry getDefaultInstanceForType() {
          return getDefaultInstance();
        }

        public org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content.Entry build() {
          org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content.Entry result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content.Entry buildPartial() {
          org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content.Entry result = new org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content.Entry(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.name_ = name_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.body_ = body_;
          result.bitField0_ = to_bitField0_;
          return result;
        }

        public Builder mergeFrom(org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content.Entry other) {
          if (other == getDefaultInstance()) return this;
          if (other.hasName()) {
            bitField0_ |= 0x00000001;
            name_ = other.name_;
            
          }
          if (other.hasBody()) {
            setBody(other.getBody());
          }
          return this;
        }

        public final boolean isInitialized() {
          if (!hasName()) {
            
            return false;
          }
          if (!hasBody()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            CodedInputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws IOException {
          org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content.Entry parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (InvalidProtocolBufferException e) {
            parsedMessage = (org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content.Entry) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string name = 1;
        private Object name_ = "";
        /**
         * <code>required string name = 1;</code>
         */
        public boolean hasName() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string name = 1;</code>
         */
        public String getName() {
          Object ref = name_;
          if (!(ref instanceof String)) {
            String s = ((ByteString) ref)
                .toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>required string name = 1;</code>
         */
        public ByteString
            getNameBytes() {
          Object ref = name_;
          if (ref instanceof String) {
            ByteString b =
                ByteString.copyFromUtf8(
                    (String) ref);
            name_ = b;
            return b;
          } else {
            return (ByteString) ref;
          }
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder setName(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          
          return this;
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder clearName() {
          bitField0_ = (bitField0_ & ~0x00000001);
          name_ = getDefaultInstance().getName();
          
          return this;
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder setNameBytes(
            ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          
          return this;
        }

        // required bytes body = 2;
        private ByteString body_ = ByteString.EMPTY;
        /**
         * <code>required bytes body = 2;</code>
         */
        public boolean hasBody() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required bytes body = 2;</code>
         */
        public ByteString getBody() {
          return body_;
        }
        /**
         * <code>required bytes body = 2;</code>
         */
        public Builder setBody(ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          body_ = value;
          
          return this;
        }
        /**
         * <code>required bytes body = 2;</code>
         */
        public Builder clearBody() {
          bitField0_ = (bitField0_ & ~0x00000002);
          body_ = getDefaultInstance().getBody();
          
          return this;
        }

        // @@protoc_insertion_point(builder_scope:org.jetbrains.kotlin.serialization.js.Content.Entry)
      }

      static {
        defaultInstance = new Entry(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:org.jetbrains.kotlin.serialization.js.Content.Entry)
    }

    // repeated .org.jetbrains.kotlin.serialization.js.Content.Entry entry = 1;
    public static final int ENTRY_FIELD_NUMBER = 1;
    private List<org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content.Entry> entry_;
    /**
     * <code>repeated .org.jetbrains.kotlin.serialization.js.Content.Entry entry = 1;</code>
     */
    public List<org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content.Entry> getEntryList() {
      return entry_;
    }
    /**
     * <code>repeated .org.jetbrains.kotlin.serialization.js.Content.Entry entry = 1;</code>
     */
    public List<? extends org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content.EntryOrBuilder>
        getEntryOrBuilderList() {
      return entry_;
    }
    /**
     * <code>repeated .org.jetbrains.kotlin.serialization.js.Content.Entry entry = 1;</code>
     */
    public int getEntryCount() {
      return entry_.size();
    }
    /**
     * <code>repeated .org.jetbrains.kotlin.serialization.js.Content.Entry entry = 1;</code>
     */
    public org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content.Entry getEntry(int index) {
      return entry_.get(index);
    }
    /**
     * <code>repeated .org.jetbrains.kotlin.serialization.js.Content.Entry entry = 1;</code>
     */
    public org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content.EntryOrBuilder getEntryOrBuilder(
        int index) {
      return entry_.get(index);
    }

    private void initFields() {
      entry_ = Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getEntryCount(); i++) {
        if (!getEntry(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(CodedOutputStream output)
                        throws IOException {
      getSerializedSize();
      for (int i = 0; i < entry_.size(); i++) {
        output.writeMessage(1, entry_.get(i));
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < entry_.size(); i++) {
        size += CodedOutputStream
          .computeMessageSize(1, entry_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws ObjectStreamException {
      return super.writeReplace();
    }

    public static org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content parseFrom(
        ByteString data)
        throws InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content parseFrom(
        ByteString data,
        ExtensionRegistryLite extensionRegistry)
        throws InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content parseFrom(byte[] data)
        throws InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content parseFrom(
        byte[] data,
        ExtensionRegistryLite extensionRegistry)
        throws InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content parseFrom(InputStream input)
        throws IOException {
      return PARSER.parseFrom(input);
    }
    public static org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content parseFrom(
        InputStream input,
        ExtensionRegistryLite extensionRegistry)
        throws IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content parseDelimitedFrom(InputStream input)
        throws IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content parseDelimitedFrom(
        InputStream input,
        ExtensionRegistryLite extensionRegistry)
        throws IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content parseFrom(
        CodedInputStream input)
        throws IOException {
      return PARSER.parseFrom(input);
    }
    public static org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content parseFrom(
        CodedInputStream input,
        ExtensionRegistryLite extensionRegistry)
        throws IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code org.jetbrains.kotlin.serialization.js.Content}
     */
    public static final class Builder extends
        GeneratedMessageLite.Builder<
          org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content, Builder>
        implements org.jetbrains.kotlin.serialization.js.JsProtoBuf.ContentOrBuilder {
      // Construct using org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        entry_ = Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      public org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content build() {
        org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content buildPartial() {
        org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content result = new org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          entry_ = Collections.unmodifiableList(entry_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.entry_ = entry_;
        return result;
      }

      public Builder mergeFrom(org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content other) {
        if (other == getDefaultInstance()) return this;
        if (!other.entry_.isEmpty()) {
          if (entry_.isEmpty()) {
            entry_ = other.entry_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureEntryIsMutable();
            entry_.addAll(other.entry_);
          }
          
        }
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getEntryCount(); i++) {
          if (!getEntry(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          CodedInputStream input,
          ExtensionRegistryLite extensionRegistry)
          throws IOException {
        org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (InvalidProtocolBufferException e) {
          parsedMessage = (org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .org.jetbrains.kotlin.serialization.js.Content.Entry entry = 1;
      private List<org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content.Entry> entry_ =
        Collections.emptyList();
      private void ensureEntryIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          entry_ = new ArrayList<org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content.Entry>(entry_);
          bitField0_ |= 0x00000001;
         }
      }

      /**
       * <code>repeated .org.jetbrains.kotlin.serialization.js.Content.Entry entry = 1;</code>
       */
      public List<org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content.Entry> getEntryList() {
        return Collections.unmodifiableList(entry_);
      }
      /**
       * <code>repeated .org.jetbrains.kotlin.serialization.js.Content.Entry entry = 1;</code>
       */
      public int getEntryCount() {
        return entry_.size();
      }
      /**
       * <code>repeated .org.jetbrains.kotlin.serialization.js.Content.Entry entry = 1;</code>
       */
      public org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content.Entry getEntry(int index) {
        return entry_.get(index);
      }
      /**
       * <code>repeated .org.jetbrains.kotlin.serialization.js.Content.Entry entry = 1;</code>
       */
      public Builder setEntry(
          int index, org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content.Entry value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntryIsMutable();
        entry_.set(index, value);

        return this;
      }
      /**
       * <code>repeated .org.jetbrains.kotlin.serialization.js.Content.Entry entry = 1;</code>
       */
      public Builder setEntry(
          int index, org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content.Entry.Builder builderForValue) {
        ensureEntryIsMutable();
        entry_.set(index, builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .org.jetbrains.kotlin.serialization.js.Content.Entry entry = 1;</code>
       */
      public Builder addEntry(org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content.Entry value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntryIsMutable();
        entry_.add(value);

        return this;
      }
      /**
       * <code>repeated .org.jetbrains.kotlin.serialization.js.Content.Entry entry = 1;</code>
       */
      public Builder addEntry(
          int index, org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content.Entry value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntryIsMutable();
        entry_.add(index, value);

        return this;
      }
      /**
       * <code>repeated .org.jetbrains.kotlin.serialization.js.Content.Entry entry = 1;</code>
       */
      public Builder addEntry(
          org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content.Entry.Builder builderForValue) {
        ensureEntryIsMutable();
        entry_.add(builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .org.jetbrains.kotlin.serialization.js.Content.Entry entry = 1;</code>
       */
      public Builder addEntry(
          int index, org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content.Entry.Builder builderForValue) {
        ensureEntryIsMutable();
        entry_.add(index, builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .org.jetbrains.kotlin.serialization.js.Content.Entry entry = 1;</code>
       */
      public Builder addAllEntry(
          Iterable<? extends org.jetbrains.kotlin.serialization.js.JsProtoBuf.Content.Entry> values) {
        ensureEntryIsMutable();
        addAll(values, entry_);

        return this;
      }
      /**
       * <code>repeated .org.jetbrains.kotlin.serialization.js.Content.Entry entry = 1;</code>
       */
      public Builder clearEntry() {
        entry_ = Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);

        return this;
      }
      /**
       * <code>repeated .org.jetbrains.kotlin.serialization.js.Content.Entry entry = 1;</code>
       */
      public Builder removeEntry(int index) {
        ensureEntryIsMutable();
        entry_.remove(index);

        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.jetbrains.kotlin.serialization.js.Content)
    }

    static {
      defaultInstance = new Content(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.jetbrains.kotlin.serialization.js.Content)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
